# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor/basic.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from primitive import float_pb2 as primitive_dot_float__pb2
from primitive import header_pb2 as primitive_dot_header__pb2
from primitive import string_pb2 as primitive_dot_string__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor/basic.proto',
  package='choreo',
  syntax='proto3',
  serialized_pb=_b('\n\x12sensor/basic.proto\x12\x06\x63horeo\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15primitive/float.proto\x1a\x16primitive/header.proto\x1a\x16primitive/string.proto\"{\n\rFluidPressure\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.choreo.Header\x12\'\n\x0e\x66luid_pressure\x18\x02 \x01(\x0b\x32\x0f.choreo.Float64\x12!\n\x08variance\x18\x03 \x01(\x0b\x32\x0f.choreo.Float64\"v\n\x0bIlluminance\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.choreo.Header\x12$\n\x0billuminance\x18\x02 \x01(\x0b\x32\x0f.choreo.Float64\x12!\n\x08variance\x18\x03 \x01(\x0b\x32\x0f.choreo.Float64\"y\n\x08Humidity\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.choreo.Header\x12*\n\x11relative_humidity\x18\x02 \x01(\x0b\x32\x0f.choreo.Float64\x12!\n\x08variance\x18\x03 \x01(\x0b\x32\x0f.choreo.Float64\"v\n\x0bTemperature\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.choreo.Header\x12$\n\x0btemperature\x18\x02 \x01(\x0b\x32\x0f.choreo.Float64\x12!\n\x08variance\x18\x03 \x01(\x0b\x32\x0f.choreo.Float64\"}\n\rTimeReference\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.choreo.Header\x12,\n\x08time_ref\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1e\n\x06source\x18\x03 \x01(\x0b\x32\x0e.choreo.StringB.Z,github.com/RobotStudio/choreo-msg/msg/sensorb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,primitive_dot_float__pb2.DESCRIPTOR,primitive_dot_header__pb2.DESCRIPTOR,primitive_dot_string__pb2.DESCRIPTOR,])




_FLUIDPRESSURE = _descriptor.Descriptor(
  name='FluidPressure',
  full_name='choreo.FluidPressure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='choreo.FluidPressure.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fluid_pressure', full_name='choreo.FluidPressure.fluid_pressure', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='variance', full_name='choreo.FluidPressure.variance', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=257,
)


_ILLUMINANCE = _descriptor.Descriptor(
  name='Illuminance',
  full_name='choreo.Illuminance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='choreo.Illuminance.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='illuminance', full_name='choreo.Illuminance.illuminance', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='variance', full_name='choreo.Illuminance.variance', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=377,
)


_HUMIDITY = _descriptor.Descriptor(
  name='Humidity',
  full_name='choreo.Humidity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='choreo.Humidity.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='relative_humidity', full_name='choreo.Humidity.relative_humidity', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='variance', full_name='choreo.Humidity.variance', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=500,
)


_TEMPERATURE = _descriptor.Descriptor(
  name='Temperature',
  full_name='choreo.Temperature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='choreo.Temperature.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='choreo.Temperature.temperature', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='variance', full_name='choreo.Temperature.variance', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=502,
  serialized_end=620,
)


_TIMEREFERENCE = _descriptor.Descriptor(
  name='TimeReference',
  full_name='choreo.TimeReference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='choreo.TimeReference.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_ref', full_name='choreo.TimeReference.time_ref', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source', full_name='choreo.TimeReference.source', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=622,
  serialized_end=747,
)

_FLUIDPRESSURE.fields_by_name['header'].message_type = primitive_dot_header__pb2._HEADER
_FLUIDPRESSURE.fields_by_name['fluid_pressure'].message_type = primitive_dot_float__pb2._FLOAT64
_FLUIDPRESSURE.fields_by_name['variance'].message_type = primitive_dot_float__pb2._FLOAT64
_ILLUMINANCE.fields_by_name['header'].message_type = primitive_dot_header__pb2._HEADER
_ILLUMINANCE.fields_by_name['illuminance'].message_type = primitive_dot_float__pb2._FLOAT64
_ILLUMINANCE.fields_by_name['variance'].message_type = primitive_dot_float__pb2._FLOAT64
_HUMIDITY.fields_by_name['header'].message_type = primitive_dot_header__pb2._HEADER
_HUMIDITY.fields_by_name['relative_humidity'].message_type = primitive_dot_float__pb2._FLOAT64
_HUMIDITY.fields_by_name['variance'].message_type = primitive_dot_float__pb2._FLOAT64
_TEMPERATURE.fields_by_name['header'].message_type = primitive_dot_header__pb2._HEADER
_TEMPERATURE.fields_by_name['temperature'].message_type = primitive_dot_float__pb2._FLOAT64
_TEMPERATURE.fields_by_name['variance'].message_type = primitive_dot_float__pb2._FLOAT64
_TIMEREFERENCE.fields_by_name['header'].message_type = primitive_dot_header__pb2._HEADER
_TIMEREFERENCE.fields_by_name['time_ref'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_TIMEREFERENCE.fields_by_name['source'].message_type = primitive_dot_string__pb2._STRING
DESCRIPTOR.message_types_by_name['FluidPressure'] = _FLUIDPRESSURE
DESCRIPTOR.message_types_by_name['Illuminance'] = _ILLUMINANCE
DESCRIPTOR.message_types_by_name['Humidity'] = _HUMIDITY
DESCRIPTOR.message_types_by_name['Temperature'] = _TEMPERATURE
DESCRIPTOR.message_types_by_name['TimeReference'] = _TIMEREFERENCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FluidPressure = _reflection.GeneratedProtocolMessageType('FluidPressure', (_message.Message,), dict(
  DESCRIPTOR = _FLUIDPRESSURE,
  __module__ = 'sensor.basic_pb2'
  # @@protoc_insertion_point(class_scope:choreo.FluidPressure)
  ))
_sym_db.RegisterMessage(FluidPressure)

Illuminance = _reflection.GeneratedProtocolMessageType('Illuminance', (_message.Message,), dict(
  DESCRIPTOR = _ILLUMINANCE,
  __module__ = 'sensor.basic_pb2'
  # @@protoc_insertion_point(class_scope:choreo.Illuminance)
  ))
_sym_db.RegisterMessage(Illuminance)

Humidity = _reflection.GeneratedProtocolMessageType('Humidity', (_message.Message,), dict(
  DESCRIPTOR = _HUMIDITY,
  __module__ = 'sensor.basic_pb2'
  # @@protoc_insertion_point(class_scope:choreo.Humidity)
  ))
_sym_db.RegisterMessage(Humidity)

Temperature = _reflection.GeneratedProtocolMessageType('Temperature', (_message.Message,), dict(
  DESCRIPTOR = _TEMPERATURE,
  __module__ = 'sensor.basic_pb2'
  # @@protoc_insertion_point(class_scope:choreo.Temperature)
  ))
_sym_db.RegisterMessage(Temperature)

TimeReference = _reflection.GeneratedProtocolMessageType('TimeReference', (_message.Message,), dict(
  DESCRIPTOR = _TIMEREFERENCE,
  __module__ = 'sensor.basic_pb2'
  # @@protoc_insertion_point(class_scope:choreo.TimeReference)
  ))
_sym_db.RegisterMessage(TimeReference)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z,github.com/RobotStudio/choreo-msg/msg/sensor'))
# @@protoc_insertion_point(module_scope)
