# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor/joint.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from primitive import float_pb2 as primitive_dot_float__pb2
from primitive import header_pb2 as primitive_dot_header__pb2
from primitive import string_pb2 as primitive_dot_string__pb2
from geometric import transform_pb2 as geometric_dot_transform__pb2
from geometric import twist_pb2 as geometric_dot_twist__pb2
from geometric import wrench_pb2 as geometric_dot_wrench__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor/joint.proto',
  package='choreo',
  syntax='proto3',
  serialized_pb=_b('\n\x12sensor/joint.proto\x12\x06\x63horeo\x1a\x15primitive/float.proto\x1a\x16primitive/header.proto\x1a\x16primitive/string.proto\x1a\x19geometric/transform.proto\x1a\x15geometric/twist.proto\x1a\x16geometric/wrench.proto\"\xb6\x01\n\nJointState\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.choreo.Header\x12\x1d\n\x05names\x18\x02 \x03(\x0b\x32\x0e.choreo.String\x12\"\n\tpositions\x18\x03 \x03(\x0b\x32\x0f.choreo.Float64\x12#\n\nvelocities\x18\x04 \x03(\x0b\x32\x0f.choreo.Float64\x12 \n\x07\x65\x66\x66orts\x18\x05 \x03(\x0b\x32\x0f.choreo.Float64\"\x9c\x01\n\x12MultiDOFJointState\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.choreo.Header\x12%\n\ntransforms\x18\x02 \x03(\x0b\x32\x11.choreo.Transform\x12\x1d\n\x06twists\x18\x03 \x03(\x0b\x32\r.choreo.Twist\x12 \n\x08wrenches\x18\x04 \x03(\x0b\x32\x0e.choreo.WrenchB.Z,github.com/RobotStudio/choreo-msg/msg/sensorb\x06proto3')
  ,
  dependencies=[primitive_dot_float__pb2.DESCRIPTOR,primitive_dot_header__pb2.DESCRIPTOR,primitive_dot_string__pb2.DESCRIPTOR,geometric_dot_transform__pb2.DESCRIPTOR,geometric_dot_twist__pb2.DESCRIPTOR,geometric_dot_wrench__pb2.DESCRIPTOR,])




_JOINTSTATE = _descriptor.Descriptor(
  name='JointState',
  full_name='choreo.JointState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='choreo.JointState.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='names', full_name='choreo.JointState.names', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='positions', full_name='choreo.JointState.positions', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocities', full_name='choreo.JointState.velocities', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='efforts', full_name='choreo.JointState.efforts', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=358,
)


_MULTIDOFJOINTSTATE = _descriptor.Descriptor(
  name='MultiDOFJointState',
  full_name='choreo.MultiDOFJointState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='choreo.MultiDOFJointState.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transforms', full_name='choreo.MultiDOFJointState.transforms', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='twists', full_name='choreo.MultiDOFJointState.twists', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wrenches', full_name='choreo.MultiDOFJointState.wrenches', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=517,
)

_JOINTSTATE.fields_by_name['header'].message_type = primitive_dot_header__pb2._HEADER
_JOINTSTATE.fields_by_name['names'].message_type = primitive_dot_string__pb2._STRING
_JOINTSTATE.fields_by_name['positions'].message_type = primitive_dot_float__pb2._FLOAT64
_JOINTSTATE.fields_by_name['velocities'].message_type = primitive_dot_float__pb2._FLOAT64
_JOINTSTATE.fields_by_name['efforts'].message_type = primitive_dot_float__pb2._FLOAT64
_MULTIDOFJOINTSTATE.fields_by_name['header'].message_type = primitive_dot_header__pb2._HEADER
_MULTIDOFJOINTSTATE.fields_by_name['transforms'].message_type = geometric_dot_transform__pb2._TRANSFORM
_MULTIDOFJOINTSTATE.fields_by_name['twists'].message_type = geometric_dot_twist__pb2._TWIST
_MULTIDOFJOINTSTATE.fields_by_name['wrenches'].message_type = geometric_dot_wrench__pb2._WRENCH
DESCRIPTOR.message_types_by_name['JointState'] = _JOINTSTATE
DESCRIPTOR.message_types_by_name['MultiDOFJointState'] = _MULTIDOFJOINTSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JointState = _reflection.GeneratedProtocolMessageType('JointState', (_message.Message,), dict(
  DESCRIPTOR = _JOINTSTATE,
  __module__ = 'sensor.joint_pb2'
  # @@protoc_insertion_point(class_scope:choreo.JointState)
  ))
_sym_db.RegisterMessage(JointState)

MultiDOFJointState = _reflection.GeneratedProtocolMessageType('MultiDOFJointState', (_message.Message,), dict(
  DESCRIPTOR = _MULTIDOFJOINTSTATE,
  __module__ = 'sensor.joint_pb2'
  # @@protoc_insertion_point(class_scope:choreo.MultiDOFJointState)
  ))
_sym_db.RegisterMessage(MultiDOFJointState)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z,github.com/RobotStudio/choreo-msg/msg/sensor'))
# @@protoc_insertion_point(module_scope)
