# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor/joystick.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from primitive import float_pb2 as primitive_dot_float__pb2
from primitive import header_pb2 as primitive_dot_header__pb2
from primitive import int_pb2 as primitive_dot_int__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor/joystick.proto',
  package='choreo',
  syntax='proto3',
  serialized_pb=_b('\n\x15sensor/joystick.proto\x12\x06\x63horeo\x1a\x15primitive/float.proto\x1a\x16primitive/header.proto\x1a\x13primitive/int.proto\"d\n\x03Joy\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.choreo.Header\x12\x1d\n\x04\x61xes\x18\x02 \x03(\x0b\x32\x0f.choreo.Float32\x12\x1e\n\x07\x62uttons\x18\x03 \x03(\x0b\x32\r.choreo.Int32\"\xae\x01\n\x0bJoyFeedback\x12.\n\x04type\x18\x01 \x01(\x0e\x32 .choreo.JoyFeedback.FeedbackType\x12\x1a\n\x02id\x18\x02 \x01(\x0b\x32\x0e.choreo.UInt32\x12\"\n\tintensity\x18\x03 \x01(\x0b\x32\x0f.choreo.Float32\"/\n\x0c\x46\x65\x65\x64\x62\x61\x63kType\x12\x07\n\x03LED\x10\x00\x12\n\n\x06RUMBLE\x10\x01\x12\n\n\x06\x42UZZER\x10\x02\"6\n\x10JoyFeedbackArray\x12\"\n\x05\x61rray\x18\x01 \x03(\x0b\x32\x13.choreo.JoyFeedbackB.Z,github.com/RobotStudio/choreo-msg/msg/sensorb\x06proto3')
  ,
  dependencies=[primitive_dot_float__pb2.DESCRIPTOR,primitive_dot_header__pb2.DESCRIPTOR,primitive_dot_int__pb2.DESCRIPTOR,])



_JOYFEEDBACK_FEEDBACKTYPE = _descriptor.EnumDescriptor(
  name='FeedbackType',
  full_name='choreo.JoyFeedback.FeedbackType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUMBLE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUZZER', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=331,
  serialized_end=378,
)
_sym_db.RegisterEnumDescriptor(_JOYFEEDBACK_FEEDBACKTYPE)


_JOY = _descriptor.Descriptor(
  name='Joy',
  full_name='choreo.Joy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='choreo.Joy.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='axes', full_name='choreo.Joy.axes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='buttons', full_name='choreo.Joy.buttons', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=201,
)


_JOYFEEDBACK = _descriptor.Descriptor(
  name='JoyFeedback',
  full_name='choreo.JoyFeedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='choreo.JoyFeedback.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='choreo.JoyFeedback.id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='intensity', full_name='choreo.JoyFeedback.intensity', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _JOYFEEDBACK_FEEDBACKTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=378,
)


_JOYFEEDBACKARRAY = _descriptor.Descriptor(
  name='JoyFeedbackArray',
  full_name='choreo.JoyFeedbackArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='array', full_name='choreo.JoyFeedbackArray.array', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=434,
)

_JOY.fields_by_name['header'].message_type = primitive_dot_header__pb2._HEADER
_JOY.fields_by_name['axes'].message_type = primitive_dot_float__pb2._FLOAT32
_JOY.fields_by_name['buttons'].message_type = primitive_dot_int__pb2._INT32
_JOYFEEDBACK.fields_by_name['type'].enum_type = _JOYFEEDBACK_FEEDBACKTYPE
_JOYFEEDBACK.fields_by_name['id'].message_type = primitive_dot_int__pb2._UINT32
_JOYFEEDBACK.fields_by_name['intensity'].message_type = primitive_dot_float__pb2._FLOAT32
_JOYFEEDBACK_FEEDBACKTYPE.containing_type = _JOYFEEDBACK
_JOYFEEDBACKARRAY.fields_by_name['array'].message_type = _JOYFEEDBACK
DESCRIPTOR.message_types_by_name['Joy'] = _JOY
DESCRIPTOR.message_types_by_name['JoyFeedback'] = _JOYFEEDBACK
DESCRIPTOR.message_types_by_name['JoyFeedbackArray'] = _JOYFEEDBACKARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Joy = _reflection.GeneratedProtocolMessageType('Joy', (_message.Message,), dict(
  DESCRIPTOR = _JOY,
  __module__ = 'sensor.joystick_pb2'
  # @@protoc_insertion_point(class_scope:choreo.Joy)
  ))
_sym_db.RegisterMessage(Joy)

JoyFeedback = _reflection.GeneratedProtocolMessageType('JoyFeedback', (_message.Message,), dict(
  DESCRIPTOR = _JOYFEEDBACK,
  __module__ = 'sensor.joystick_pb2'
  # @@protoc_insertion_point(class_scope:choreo.JoyFeedback)
  ))
_sym_db.RegisterMessage(JoyFeedback)

JoyFeedbackArray = _reflection.GeneratedProtocolMessageType('JoyFeedbackArray', (_message.Message,), dict(
  DESCRIPTOR = _JOYFEEDBACKARRAY,
  __module__ = 'sensor.joystick_pb2'
  # @@protoc_insertion_point(class_scope:choreo.JoyFeedbackArray)
  ))
_sym_db.RegisterMessage(JoyFeedbackArray)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z,github.com/RobotStudio/choreo-msg/msg/sensor'))
# @@protoc_insertion_point(module_scope)
