# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from msg.primitive import string_pb2 as msg_dot_primitive_dot_string__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='echo.proto',
  package='choreo',
  syntax='proto3',
  serialized_options=_b('Z%github.com/RobotStudio/choreo-svc/svc'),
  serialized_pb=_b('\n\necho.proto\x12\x06\x63horeo\x1a\x1amsg/primitive/string.proto20\n\x04\x45\x63ho\x12(\n\x04\x45\x63ho\x12\x0e.choreo.String\x1a\x0e.choreo.String\"\x00\x42\'Z%github.com/RobotStudio/choreo-svc/svcb\x06proto3')
  ,
  dependencies=[msg_dot_primitive_dot_string__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_ECHO = _descriptor.ServiceDescriptor(
  name='Echo',
  full_name='choreo.Echo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=50,
  serialized_end=98,
  methods=[
  _descriptor.MethodDescriptor(
    name='Echo',
    full_name='choreo.Echo.Echo',
    index=0,
    containing_service=None,
    input_type=msg_dot_primitive_dot_string__pb2._STRING,
    output_type=msg_dot_primitive_dot_string__pb2._STRING,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ECHO)

DESCRIPTOR.services_by_name['Echo'] = _ECHO

# @@protoc_insertion_point(module_scope)
