# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ping.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from primitive import bool_pb2 as primitive_dot_bool__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ping.proto',
  package='choreo',
  syntax='proto3',
  serialized_pb=_b('\n\nping.proto\x12\x06\x63horeo\x1a\x14primitive/bool.proto2,\n\x04Ping\x12$\n\x04Ping\x12\x0c.choreo.Bool\x1a\x0c.choreo.Bool\"\x00\x42\'Z%github.com/RobotStudio/choreo-svc/svcb\x06proto3')
  ,
  dependencies=[primitive_dot_bool__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z%github.com/RobotStudio/choreo-svc/svc'))
# @@protoc_insertion_point(module_scope)
