# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: diagnostic/diagnostic.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from primitive import bool_pb2 as primitive_dot_bool__pb2
from primitive import header_pb2 as primitive_dot_header__pb2
from primitive import string_pb2 as primitive_dot_string__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='diagnostic/diagnostic.proto',
  package='choreo',
  syntax='proto3',
  serialized_pb=_b('\n\x1b\x64iagnostic/diagnostic.proto\x12\x06\x63horeo\x1a\x14primitive/bool.proto\x1a\x16primitive/header.proto\x1a\x16primitive/string.proto\"F\n\x08KeyValue\x12\x1b\n\x03key\x18\x01 \x01(\x0b\x32\x0e.choreo.String\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.choreo.String\"\xf8\x01\n\x10\x44iagnosticStatus\x12-\n\x05level\x18\x01 \x01(\x0e\x32\x1e.choreo.DiagnosticStatus.Level\x12\x1c\n\x04name\x18\x02 \x01(\x0b\x32\x0e.choreo.String\x12\x1f\n\x07message\x18\x03 \x01(\x0b\x32\x0e.choreo.String\x12#\n\x0bhardware_id\x18\x04 \x01(\x0b\x32\x0e.choreo.String\x12 \n\x06values\x18\x05 \x03(\x0b\x32\x10.choreo.KeyValue\"/\n\x05Level\x12\x06\n\x02OK\x10\x00\x12\x08\n\x04WARN\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\t\n\x05STALE\x10\x03\"[\n\x0f\x44iagnosticArray\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.choreo.Header\x12(\n\x06status\x18\x02 \x03(\x0b\x32\x18.choreo.DiagnosticStatus\"q\n\x0fServiceResponse\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.choreo.Header\x12\x1d\n\x07success\x18\x02 \x01(\x0b\x32\x0c.choreo.Bool\x12\x1f\n\x07message\x18\x03 \x01(\x0b\x32\x0e.choreo.String\"u\n\x0fServiceSelfTest\x12\x1a\n\x02id\x18\x01 \x01(\x0b\x32\x0e.choreo.String\x12\x1c\n\x06passed\x18\x02 \x01(\x0b\x32\x0c.choreo.Bool\x12(\n\x06status\x18\x03 \x03(\x0b\x32\x18.choreo.DiagnosticStatusB2Z0github.com/RobotStudio/choreo-msg/msg/diagnosticb\x06proto3')
  ,
  dependencies=[primitive_dot_bool__pb2.DESCRIPTOR,primitive_dot_header__pb2.DESCRIPTOR,primitive_dot_string__pb2.DESCRIPTOR,])



_DIAGNOSTICSTATUS_LEVEL = _descriptor.EnumDescriptor(
  name='Level',
  full_name='choreo.DiagnosticStatus.Level',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WARN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STALE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=383,
  serialized_end=430,
)
_sym_db.RegisterEnumDescriptor(_DIAGNOSTICSTATUS_LEVEL)


_KEYVALUE = _descriptor.Descriptor(
  name='KeyValue',
  full_name='choreo.KeyValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='choreo.KeyValue.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='choreo.KeyValue.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=179,
)


_DIAGNOSTICSTATUS = _descriptor.Descriptor(
  name='DiagnosticStatus',
  full_name='choreo.DiagnosticStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='level', full_name='choreo.DiagnosticStatus.level', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='choreo.DiagnosticStatus.name', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='choreo.DiagnosticStatus.message', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hardware_id', full_name='choreo.DiagnosticStatus.hardware_id', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='choreo.DiagnosticStatus.values', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DIAGNOSTICSTATUS_LEVEL,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=430,
)


_DIAGNOSTICARRAY = _descriptor.Descriptor(
  name='DiagnosticArray',
  full_name='choreo.DiagnosticArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='choreo.DiagnosticArray.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='choreo.DiagnosticArray.status', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=523,
)


_SERVICERESPONSE = _descriptor.Descriptor(
  name='ServiceResponse',
  full_name='choreo.ServiceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='choreo.ServiceResponse.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='success', full_name='choreo.ServiceResponse.success', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='choreo.ServiceResponse.message', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=525,
  serialized_end=638,
)


_SERVICESELFTEST = _descriptor.Descriptor(
  name='ServiceSelfTest',
  full_name='choreo.ServiceSelfTest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='choreo.ServiceSelfTest.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='passed', full_name='choreo.ServiceSelfTest.passed', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='choreo.ServiceSelfTest.status', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=640,
  serialized_end=757,
)

_KEYVALUE.fields_by_name['key'].message_type = primitive_dot_string__pb2._STRING
_KEYVALUE.fields_by_name['value'].message_type = primitive_dot_string__pb2._STRING
_DIAGNOSTICSTATUS.fields_by_name['level'].enum_type = _DIAGNOSTICSTATUS_LEVEL
_DIAGNOSTICSTATUS.fields_by_name['name'].message_type = primitive_dot_string__pb2._STRING
_DIAGNOSTICSTATUS.fields_by_name['message'].message_type = primitive_dot_string__pb2._STRING
_DIAGNOSTICSTATUS.fields_by_name['hardware_id'].message_type = primitive_dot_string__pb2._STRING
_DIAGNOSTICSTATUS.fields_by_name['values'].message_type = _KEYVALUE
_DIAGNOSTICSTATUS_LEVEL.containing_type = _DIAGNOSTICSTATUS
_DIAGNOSTICARRAY.fields_by_name['header'].message_type = primitive_dot_header__pb2._HEADER
_DIAGNOSTICARRAY.fields_by_name['status'].message_type = _DIAGNOSTICSTATUS
_SERVICERESPONSE.fields_by_name['header'].message_type = primitive_dot_header__pb2._HEADER
_SERVICERESPONSE.fields_by_name['success'].message_type = primitive_dot_bool__pb2._BOOL
_SERVICERESPONSE.fields_by_name['message'].message_type = primitive_dot_string__pb2._STRING
_SERVICESELFTEST.fields_by_name['id'].message_type = primitive_dot_string__pb2._STRING
_SERVICESELFTEST.fields_by_name['passed'].message_type = primitive_dot_bool__pb2._BOOL
_SERVICESELFTEST.fields_by_name['status'].message_type = _DIAGNOSTICSTATUS
DESCRIPTOR.message_types_by_name['KeyValue'] = _KEYVALUE
DESCRIPTOR.message_types_by_name['DiagnosticStatus'] = _DIAGNOSTICSTATUS
DESCRIPTOR.message_types_by_name['DiagnosticArray'] = _DIAGNOSTICARRAY
DESCRIPTOR.message_types_by_name['ServiceResponse'] = _SERVICERESPONSE
DESCRIPTOR.message_types_by_name['ServiceSelfTest'] = _SERVICESELFTEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KeyValue = _reflection.GeneratedProtocolMessageType('KeyValue', (_message.Message,), dict(
  DESCRIPTOR = _KEYVALUE,
  __module__ = 'diagnostic.diagnostic_pb2'
  # @@protoc_insertion_point(class_scope:choreo.KeyValue)
  ))
_sym_db.RegisterMessage(KeyValue)

DiagnosticStatus = _reflection.GeneratedProtocolMessageType('DiagnosticStatus', (_message.Message,), dict(
  DESCRIPTOR = _DIAGNOSTICSTATUS,
  __module__ = 'diagnostic.diagnostic_pb2'
  # @@protoc_insertion_point(class_scope:choreo.DiagnosticStatus)
  ))
_sym_db.RegisterMessage(DiagnosticStatus)

DiagnosticArray = _reflection.GeneratedProtocolMessageType('DiagnosticArray', (_message.Message,), dict(
  DESCRIPTOR = _DIAGNOSTICARRAY,
  __module__ = 'diagnostic.diagnostic_pb2'
  # @@protoc_insertion_point(class_scope:choreo.DiagnosticArray)
  ))
_sym_db.RegisterMessage(DiagnosticArray)

ServiceResponse = _reflection.GeneratedProtocolMessageType('ServiceResponse', (_message.Message,), dict(
  DESCRIPTOR = _SERVICERESPONSE,
  __module__ = 'diagnostic.diagnostic_pb2'
  # @@protoc_insertion_point(class_scope:choreo.ServiceResponse)
  ))
_sym_db.RegisterMessage(ServiceResponse)

ServiceSelfTest = _reflection.GeneratedProtocolMessageType('ServiceSelfTest', (_message.Message,), dict(
  DESCRIPTOR = _SERVICESELFTEST,
  __module__ = 'diagnostic.diagnostic_pb2'
  # @@protoc_insertion_point(class_scope:choreo.ServiceSelfTest)
  ))
_sym_db.RegisterMessage(ServiceSelfTest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z0github.com/RobotStudio/choreo-msg/msg/diagnostic'))
# @@protoc_insertion_point(module_scope)
