# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: primitive/double.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='primitive/double.proto',
  package='choreo',
  syntax='proto3',
  serialized_pb=_b('\n\x16primitive/double.proto\x12\x06\x63horeo\"+\n\x0b\x44oubleArray\x12\x1c\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x0e.choreo.Double\"\x16\n\x06\x44ouble\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x01\x42\x31Z/github.com/RobotStudio/choreo-msg/msg/primitiveb\x06proto3')
)




_DOUBLEARRAY = _descriptor.Descriptor(
  name='DoubleArray',
  full_name='choreo.DoubleArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='choreo.DoubleArray.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=77,
)


_DOUBLE = _descriptor.Descriptor(
  name='Double',
  full_name='choreo.Double',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='choreo.Double.data', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=101,
)

_DOUBLEARRAY.fields_by_name['data'].message_type = _DOUBLE
DESCRIPTOR.message_types_by_name['DoubleArray'] = _DOUBLEARRAY
DESCRIPTOR.message_types_by_name['Double'] = _DOUBLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DoubleArray = _reflection.GeneratedProtocolMessageType('DoubleArray', (_message.Message,), dict(
  DESCRIPTOR = _DOUBLEARRAY,
  __module__ = 'primitive.double_pb2'
  # @@protoc_insertion_point(class_scope:choreo.DoubleArray)
  ))
_sym_db.RegisterMessage(DoubleArray)

Double = _reflection.GeneratedProtocolMessageType('Double', (_message.Message,), dict(
  DESCRIPTOR = _DOUBLE,
  __module__ = 'primitive.double_pb2'
  # @@protoc_insertion_point(class_scope:choreo.Double)
  ))
_sym_db.RegisterMessage(Double)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z/github.com/RobotStudio/choreo-msg/msg/primitive'))
# @@protoc_insertion_point(module_scope)
