# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: primitive/fixed.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='primitive/fixed.proto',
  package='choreo',
  syntax='proto3',
  serialized_pb=_b('\n\x15primitive/fixed.proto\x12\x06\x63horeo\"-\n\x0c\x46ixed32Array\x12\x1d\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x0f.choreo.Fixed32\"\x17\n\x07\x46ixed32\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\r\"-\n\x0c\x46ixed64Array\x12\x1d\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x0f.choreo.Fixed64\"\x17\n\x07\x46ixed64\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x04\x42\x31Z/github.com/RobotStudio/choreo-msg/msg/primitiveb\x06proto3')
)




_FIXED32ARRAY = _descriptor.Descriptor(
  name='Fixed32Array',
  full_name='choreo.Fixed32Array',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='choreo.Fixed32Array.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=78,
)


_FIXED32 = _descriptor.Descriptor(
  name='Fixed32',
  full_name='choreo.Fixed32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='choreo.Fixed32.data', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=103,
)


_FIXED64ARRAY = _descriptor.Descriptor(
  name='Fixed64Array',
  full_name='choreo.Fixed64Array',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='choreo.Fixed64Array.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=150,
)


_FIXED64 = _descriptor.Descriptor(
  name='Fixed64',
  full_name='choreo.Fixed64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='choreo.Fixed64.data', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=175,
)

_FIXED32ARRAY.fields_by_name['data'].message_type = _FIXED32
_FIXED64ARRAY.fields_by_name['data'].message_type = _FIXED64
DESCRIPTOR.message_types_by_name['Fixed32Array'] = _FIXED32ARRAY
DESCRIPTOR.message_types_by_name['Fixed32'] = _FIXED32
DESCRIPTOR.message_types_by_name['Fixed64Array'] = _FIXED64ARRAY
DESCRIPTOR.message_types_by_name['Fixed64'] = _FIXED64
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Fixed32Array = _reflection.GeneratedProtocolMessageType('Fixed32Array', (_message.Message,), dict(
  DESCRIPTOR = _FIXED32ARRAY,
  __module__ = 'primitive.fixed_pb2'
  # @@protoc_insertion_point(class_scope:choreo.Fixed32Array)
  ))
_sym_db.RegisterMessage(Fixed32Array)

Fixed32 = _reflection.GeneratedProtocolMessageType('Fixed32', (_message.Message,), dict(
  DESCRIPTOR = _FIXED32,
  __module__ = 'primitive.fixed_pb2'
  # @@protoc_insertion_point(class_scope:choreo.Fixed32)
  ))
_sym_db.RegisterMessage(Fixed32)

Fixed64Array = _reflection.GeneratedProtocolMessageType('Fixed64Array', (_message.Message,), dict(
  DESCRIPTOR = _FIXED64ARRAY,
  __module__ = 'primitive.fixed_pb2'
  # @@protoc_insertion_point(class_scope:choreo.Fixed64Array)
  ))
_sym_db.RegisterMessage(Fixed64Array)

Fixed64 = _reflection.GeneratedProtocolMessageType('Fixed64', (_message.Message,), dict(
  DESCRIPTOR = _FIXED64,
  __module__ = 'primitive.fixed_pb2'
  # @@protoc_insertion_point(class_scope:choreo.Fixed64)
  ))
_sym_db.RegisterMessage(Fixed64)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z/github.com/RobotStudio/choreo-msg/msg/primitive'))
# @@protoc_insertion_point(module_scope)
