# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geometric/point.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from primitive import header_pb2 as primitive_dot_header__pb2
from primitive import float_pb2 as primitive_dot_float__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='geometric/point.proto',
  package='choreo',
  syntax='proto3',
  serialized_pb=_b('\n\x15geometric/point.proto\x12\x06\x63horeo\x1a\x16primitive/header.proto\x1a\x15primitive/float.proto\"P\n\x0ePoint32Stamped\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.choreo.Header\x12\x1e\n\x05point\x18\x02 \x01(\x0b\x32\x0f.choreo.Point32\"L\n\x0cPointStamped\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.choreo.Header\x12\x1c\n\x05point\x18\x02 \x01(\x0b\x32\r.choreo.Point\"]\n\x07Point32\x12\x1a\n\x01x\x18\x01 \x01(\x0b\x32\x0f.choreo.Float32\x12\x1a\n\x01y\x18\x02 \x01(\x0b\x32\x0f.choreo.Float32\x12\x1a\n\x01z\x18\x03 \x01(\x0b\x32\x0f.choreo.Float32\"[\n\x05Point\x12\x1a\n\x01x\x18\x01 \x01(\x0b\x32\x0f.choreo.Float64\x12\x1a\n\x01y\x18\x02 \x01(\x0b\x32\x0f.choreo.Float64\x12\x1a\n\x01z\x18\x03 \x01(\x0b\x32\x0f.choreo.Float64B1Z/github.com/RobotStudio/choreo-msg/msg/geometricb\x06proto3')
  ,
  dependencies=[primitive_dot_header__pb2.DESCRIPTOR,primitive_dot_float__pb2.DESCRIPTOR,])




_POINT32STAMPED = _descriptor.Descriptor(
  name='Point32Stamped',
  full_name='choreo.Point32Stamped',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='choreo.Point32Stamped.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point', full_name='choreo.Point32Stamped.point', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=160,
)


_POINTSTAMPED = _descriptor.Descriptor(
  name='PointStamped',
  full_name='choreo.PointStamped',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='choreo.PointStamped.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point', full_name='choreo.PointStamped.point', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=238,
)


_POINT32 = _descriptor.Descriptor(
  name='Point32',
  full_name='choreo.Point32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='choreo.Point32.x', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='choreo.Point32.y', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='choreo.Point32.z', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=333,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='choreo.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='choreo.Point.x', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='choreo.Point.y', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='choreo.Point.z', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=426,
)

_POINT32STAMPED.fields_by_name['header'].message_type = primitive_dot_header__pb2._HEADER
_POINT32STAMPED.fields_by_name['point'].message_type = _POINT32
_POINTSTAMPED.fields_by_name['header'].message_type = primitive_dot_header__pb2._HEADER
_POINTSTAMPED.fields_by_name['point'].message_type = _POINT
_POINT32.fields_by_name['x'].message_type = primitive_dot_float__pb2._FLOAT32
_POINT32.fields_by_name['y'].message_type = primitive_dot_float__pb2._FLOAT32
_POINT32.fields_by_name['z'].message_type = primitive_dot_float__pb2._FLOAT32
_POINT.fields_by_name['x'].message_type = primitive_dot_float__pb2._FLOAT64
_POINT.fields_by_name['y'].message_type = primitive_dot_float__pb2._FLOAT64
_POINT.fields_by_name['z'].message_type = primitive_dot_float__pb2._FLOAT64
DESCRIPTOR.message_types_by_name['Point32Stamped'] = _POINT32STAMPED
DESCRIPTOR.message_types_by_name['PointStamped'] = _POINTSTAMPED
DESCRIPTOR.message_types_by_name['Point32'] = _POINT32
DESCRIPTOR.message_types_by_name['Point'] = _POINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Point32Stamped = _reflection.GeneratedProtocolMessageType('Point32Stamped', (_message.Message,), dict(
  DESCRIPTOR = _POINT32STAMPED,
  __module__ = 'geometric.point_pb2'
  # @@protoc_insertion_point(class_scope:choreo.Point32Stamped)
  ))
_sym_db.RegisterMessage(Point32Stamped)

PointStamped = _reflection.GeneratedProtocolMessageType('PointStamped', (_message.Message,), dict(
  DESCRIPTOR = _POINTSTAMPED,
  __module__ = 'geometric.point_pb2'
  # @@protoc_insertion_point(class_scope:choreo.PointStamped)
  ))
_sym_db.RegisterMessage(PointStamped)

Point32 = _reflection.GeneratedProtocolMessageType('Point32', (_message.Message,), dict(
  DESCRIPTOR = _POINT32,
  __module__ = 'geometric.point_pb2'
  # @@protoc_insertion_point(class_scope:choreo.Point32)
  ))
_sym_db.RegisterMessage(Point32)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'geometric.point_pb2'
  # @@protoc_insertion_point(class_scope:choreo.Point)
  ))
_sym_db.RegisterMessage(Point)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z/github.com/RobotStudio/choreo-msg/msg/geometric'))
# @@protoc_insertion_point(module_scope)
