# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geometric/polygon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from primitive import header_pb2 as primitive_dot_header__pb2
from geometric import point_pb2 as geometric_dot_point__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='geometric/polygon.proto',
  package='choreo',
  syntax='proto3',
  serialized_pb=_b('\n\x17geometric/polygon.proto\x12\x06\x63horeo\x1a\x16primitive/header.proto\x1a\x15geometric/point.proto\"R\n\x0ePolygonStamped\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.choreo.Header\x12 \n\x07polygon\x18\x02 \x01(\x0b\x32\x0f.choreo.Polygon\"V\n\x10Polygon32Stamped\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.choreo.Header\x12\"\n\x07polygon\x18\x02 \x01(\x0b\x32\x11.choreo.Polygon32\"(\n\x07Polygon\x12\x1d\n\x06points\x18\x01 \x03(\x0b\x32\r.choreo.Point\",\n\tPolygon32\x12\x1f\n\x06points\x18\x01 \x03(\x0b\x32\x0f.choreo.Point32B1Z/github.com/RobotStudio/choreo-msg/msg/geometricb\x06proto3')
  ,
  dependencies=[primitive_dot_header__pb2.DESCRIPTOR,geometric_dot_point__pb2.DESCRIPTOR,])




_POLYGONSTAMPED = _descriptor.Descriptor(
  name='PolygonStamped',
  full_name='choreo.PolygonStamped',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='choreo.PolygonStamped.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='polygon', full_name='choreo.PolygonStamped.polygon', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=164,
)


_POLYGON32STAMPED = _descriptor.Descriptor(
  name='Polygon32Stamped',
  full_name='choreo.Polygon32Stamped',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='choreo.Polygon32Stamped.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='polygon', full_name='choreo.Polygon32Stamped.polygon', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=252,
)


_POLYGON = _descriptor.Descriptor(
  name='Polygon',
  full_name='choreo.Polygon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='choreo.Polygon.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=294,
)


_POLYGON32 = _descriptor.Descriptor(
  name='Polygon32',
  full_name='choreo.Polygon32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='choreo.Polygon32.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=340,
)

_POLYGONSTAMPED.fields_by_name['header'].message_type = primitive_dot_header__pb2._HEADER
_POLYGONSTAMPED.fields_by_name['polygon'].message_type = _POLYGON
_POLYGON32STAMPED.fields_by_name['header'].message_type = primitive_dot_header__pb2._HEADER
_POLYGON32STAMPED.fields_by_name['polygon'].message_type = _POLYGON32
_POLYGON.fields_by_name['points'].message_type = geometric_dot_point__pb2._POINT
_POLYGON32.fields_by_name['points'].message_type = geometric_dot_point__pb2._POINT32
DESCRIPTOR.message_types_by_name['PolygonStamped'] = _POLYGONSTAMPED
DESCRIPTOR.message_types_by_name['Polygon32Stamped'] = _POLYGON32STAMPED
DESCRIPTOR.message_types_by_name['Polygon'] = _POLYGON
DESCRIPTOR.message_types_by_name['Polygon32'] = _POLYGON32
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PolygonStamped = _reflection.GeneratedProtocolMessageType('PolygonStamped', (_message.Message,), dict(
  DESCRIPTOR = _POLYGONSTAMPED,
  __module__ = 'geometric.polygon_pb2'
  # @@protoc_insertion_point(class_scope:choreo.PolygonStamped)
  ))
_sym_db.RegisterMessage(PolygonStamped)

Polygon32Stamped = _reflection.GeneratedProtocolMessageType('Polygon32Stamped', (_message.Message,), dict(
  DESCRIPTOR = _POLYGON32STAMPED,
  __module__ = 'geometric.polygon_pb2'
  # @@protoc_insertion_point(class_scope:choreo.Polygon32Stamped)
  ))
_sym_db.RegisterMessage(Polygon32Stamped)

Polygon = _reflection.GeneratedProtocolMessageType('Polygon', (_message.Message,), dict(
  DESCRIPTOR = _POLYGON,
  __module__ = 'geometric.polygon_pb2'
  # @@protoc_insertion_point(class_scope:choreo.Polygon)
  ))
_sym_db.RegisterMessage(Polygon)

Polygon32 = _reflection.GeneratedProtocolMessageType('Polygon32', (_message.Message,), dict(
  DESCRIPTOR = _POLYGON32,
  __module__ = 'geometric.polygon_pb2'
  # @@protoc_insertion_point(class_scope:choreo.Polygon32)
  ))
_sym_db.RegisterMessage(Polygon32)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z/github.com/RobotStudio/choreo-msg/msg/geometric'))
# @@protoc_insertion_point(module_scope)
