# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geometric/quaternion.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from primitive import header_pb2 as primitive_dot_header__pb2
from primitive import float_pb2 as primitive_dot_float__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='geometric/quaternion.proto',
  package='choreo',
  syntax='proto3',
  serialized_pb=_b('\n\x1ageometric/quaternion.proto\x12\x06\x63horeo\x1a\x16primitive/header.proto\x1a\x15primitive/float.proto\"[\n\x11QuaternionStamped\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.choreo.Header\x12&\n\nquaternion\x18\x02 \x01(\x0b\x32\x12.choreo.Quaternion\"|\n\nQuaternion\x12\x1a\n\x01x\x18\x01 \x01(\x0b\x32\x0f.choreo.Float64\x12\x1a\n\x01y\x18\x02 \x01(\x0b\x32\x0f.choreo.Float64\x12\x1a\n\x01z\x18\x03 \x01(\x0b\x32\x0f.choreo.Float64\x12\x1a\n\x01w\x18\x04 \x01(\x0b\x32\x0f.choreo.Float64B1Z/github.com/RobotStudio/choreo-msg/msg/geometricb\x06proto3')
  ,
  dependencies=[primitive_dot_header__pb2.DESCRIPTOR,primitive_dot_float__pb2.DESCRIPTOR,])




_QUATERNIONSTAMPED = _descriptor.Descriptor(
  name='QuaternionStamped',
  full_name='choreo.QuaternionStamped',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='choreo.QuaternionStamped.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quaternion', full_name='choreo.QuaternionStamped.quaternion', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=176,
)


_QUATERNION = _descriptor.Descriptor(
  name='Quaternion',
  full_name='choreo.Quaternion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='choreo.Quaternion.x', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='choreo.Quaternion.y', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='choreo.Quaternion.z', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='w', full_name='choreo.Quaternion.w', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=302,
)

_QUATERNIONSTAMPED.fields_by_name['header'].message_type = primitive_dot_header__pb2._HEADER
_QUATERNIONSTAMPED.fields_by_name['quaternion'].message_type = _QUATERNION
_QUATERNION.fields_by_name['x'].message_type = primitive_dot_float__pb2._FLOAT64
_QUATERNION.fields_by_name['y'].message_type = primitive_dot_float__pb2._FLOAT64
_QUATERNION.fields_by_name['z'].message_type = primitive_dot_float__pb2._FLOAT64
_QUATERNION.fields_by_name['w'].message_type = primitive_dot_float__pb2._FLOAT64
DESCRIPTOR.message_types_by_name['QuaternionStamped'] = _QUATERNIONSTAMPED
DESCRIPTOR.message_types_by_name['Quaternion'] = _QUATERNION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QuaternionStamped = _reflection.GeneratedProtocolMessageType('QuaternionStamped', (_message.Message,), dict(
  DESCRIPTOR = _QUATERNIONSTAMPED,
  __module__ = 'geometric.quaternion_pb2'
  # @@protoc_insertion_point(class_scope:choreo.QuaternionStamped)
  ))
_sym_db.RegisterMessage(QuaternionStamped)

Quaternion = _reflection.GeneratedProtocolMessageType('Quaternion', (_message.Message,), dict(
  DESCRIPTOR = _QUATERNION,
  __module__ = 'geometric.quaternion_pb2'
  # @@protoc_insertion_point(class_scope:choreo.Quaternion)
  ))
_sym_db.RegisterMessage(Quaternion)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z/github.com/RobotStudio/choreo-msg/msg/geometric'))
# @@protoc_insertion_point(module_scope)
