# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geometric/twist.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from primitive import header_pb2 as primitive_dot_header__pb2
from primitive import float_pb2 as primitive_dot_float__pb2
from geometric import vector_pb2 as geometric_dot_vector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='geometric/twist.proto',
  package='choreo',
  syntax='proto3',
  serialized_pb=_b('\n\x15geometric/twist.proto\x12\x06\x63horeo\x1a\x16primitive/header.proto\x1a\x15primitive/float.proto\x1a\x16geometric/vector.proto\"L\n\x0cTwistStamped\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.choreo.Header\x12\x1c\n\x05twist\x18\x02 \x01(\x0b\x32\r.choreo.Twist\"h\n\x1aTwistWithCovarianceStamped\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.choreo.Header\x12*\n\x05twist\x18\x02 \x01(\x0b\x32\x1b.choreo.TwistWithCovariance\"J\n\x05Twist\x12\x1f\n\x06linear\x18\x01 \x01(\x0b\x32\x0f.choreo.Vector3\x12 \n\x07\x61ngular\x18\x02 \x01(\x0b\x32\x0f.choreo.Vector3\"X\n\x13TwistWithCovariance\x12\x1c\n\x05twist\x18\x01 \x01(\x0b\x32\r.choreo.Twist\x12#\n\ncovariance\x18\x02 \x03(\x0b\x32\x0f.choreo.Float64B1Z/github.com/RobotStudio/choreo-msg/msg/geometricb\x06proto3')
  ,
  dependencies=[primitive_dot_header__pb2.DESCRIPTOR,primitive_dot_float__pb2.DESCRIPTOR,geometric_dot_vector__pb2.DESCRIPTOR,])




_TWISTSTAMPED = _descriptor.Descriptor(
  name='TwistStamped',
  full_name='choreo.TwistStamped',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='choreo.TwistStamped.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='twist', full_name='choreo.TwistStamped.twist', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=180,
)


_TWISTWITHCOVARIANCESTAMPED = _descriptor.Descriptor(
  name='TwistWithCovarianceStamped',
  full_name='choreo.TwistWithCovarianceStamped',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='choreo.TwistWithCovarianceStamped.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='twist', full_name='choreo.TwistWithCovarianceStamped.twist', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=286,
)


_TWIST = _descriptor.Descriptor(
  name='Twist',
  full_name='choreo.Twist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='linear', full_name='choreo.Twist.linear', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='angular', full_name='choreo.Twist.angular', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=362,
)


_TWISTWITHCOVARIANCE = _descriptor.Descriptor(
  name='TwistWithCovariance',
  full_name='choreo.TwistWithCovariance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='twist', full_name='choreo.TwistWithCovariance.twist', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='covariance', full_name='choreo.TwistWithCovariance.covariance', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=364,
  serialized_end=452,
)

_TWISTSTAMPED.fields_by_name['header'].message_type = primitive_dot_header__pb2._HEADER
_TWISTSTAMPED.fields_by_name['twist'].message_type = _TWIST
_TWISTWITHCOVARIANCESTAMPED.fields_by_name['header'].message_type = primitive_dot_header__pb2._HEADER
_TWISTWITHCOVARIANCESTAMPED.fields_by_name['twist'].message_type = _TWISTWITHCOVARIANCE
_TWIST.fields_by_name['linear'].message_type = geometric_dot_vector__pb2._VECTOR3
_TWIST.fields_by_name['angular'].message_type = geometric_dot_vector__pb2._VECTOR3
_TWISTWITHCOVARIANCE.fields_by_name['twist'].message_type = _TWIST
_TWISTWITHCOVARIANCE.fields_by_name['covariance'].message_type = primitive_dot_float__pb2._FLOAT64
DESCRIPTOR.message_types_by_name['TwistStamped'] = _TWISTSTAMPED
DESCRIPTOR.message_types_by_name['TwistWithCovarianceStamped'] = _TWISTWITHCOVARIANCESTAMPED
DESCRIPTOR.message_types_by_name['Twist'] = _TWIST
DESCRIPTOR.message_types_by_name['TwistWithCovariance'] = _TWISTWITHCOVARIANCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TwistStamped = _reflection.GeneratedProtocolMessageType('TwistStamped', (_message.Message,), dict(
  DESCRIPTOR = _TWISTSTAMPED,
  __module__ = 'geometric.twist_pb2'
  # @@protoc_insertion_point(class_scope:choreo.TwistStamped)
  ))
_sym_db.RegisterMessage(TwistStamped)

TwistWithCovarianceStamped = _reflection.GeneratedProtocolMessageType('TwistWithCovarianceStamped', (_message.Message,), dict(
  DESCRIPTOR = _TWISTWITHCOVARIANCESTAMPED,
  __module__ = 'geometric.twist_pb2'
  # @@protoc_insertion_point(class_scope:choreo.TwistWithCovarianceStamped)
  ))
_sym_db.RegisterMessage(TwistWithCovarianceStamped)

Twist = _reflection.GeneratedProtocolMessageType('Twist', (_message.Message,), dict(
  DESCRIPTOR = _TWIST,
  __module__ = 'geometric.twist_pb2'
  # @@protoc_insertion_point(class_scope:choreo.Twist)
  ))
_sym_db.RegisterMessage(Twist)

TwistWithCovariance = _reflection.GeneratedProtocolMessageType('TwistWithCovariance', (_message.Message,), dict(
  DESCRIPTOR = _TWISTWITHCOVARIANCE,
  __module__ = 'geometric.twist_pb2'
  # @@protoc_insertion_point(class_scope:choreo.TwistWithCovariance)
  ))
_sym_db.RegisterMessage(TwistWithCovariance)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z/github.com/RobotStudio/choreo-msg/msg/geometric'))
# @@protoc_insertion_point(module_scope)
