# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geometric/vector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from primitive import header_pb2 as primitive_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='geometric/vector.proto',
  package='choreo',
  syntax='proto3',
  serialized_pb=_b('\n\x16geometric/vector.proto\x12\x06\x63horeo\x1a\x16primitive/header.proto\"Q\n\x0eVector3Stamped\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.choreo.Header\x12\x1f\n\x06vector\x18\x02 \x01(\x0b\x32\x0f.choreo.Vector3\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x42\x31Z/github.com/RobotStudio/choreo-msg/msg/geometricb\x06proto3')
  ,
  dependencies=[primitive_dot_header__pb2.DESCRIPTOR,])




_VECTOR3STAMPED = _descriptor.Descriptor(
  name='Vector3Stamped',
  full_name='choreo.Vector3Stamped',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='choreo.Vector3Stamped.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vector', full_name='choreo.Vector3Stamped.vector', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=139,
)


_VECTOR3 = _descriptor.Descriptor(
  name='Vector3',
  full_name='choreo.Vector3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='choreo.Vector3.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='choreo.Vector3.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='choreo.Vector3.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=183,
)

_VECTOR3STAMPED.fields_by_name['header'].message_type = primitive_dot_header__pb2._HEADER
_VECTOR3STAMPED.fields_by_name['vector'].message_type = _VECTOR3
DESCRIPTOR.message_types_by_name['Vector3Stamped'] = _VECTOR3STAMPED
DESCRIPTOR.message_types_by_name['Vector3'] = _VECTOR3
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vector3Stamped = _reflection.GeneratedProtocolMessageType('Vector3Stamped', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR3STAMPED,
  __module__ = 'geometric.vector_pb2'
  # @@protoc_insertion_point(class_scope:choreo.Vector3Stamped)
  ))
_sym_db.RegisterMessage(Vector3Stamped)

Vector3 = _reflection.GeneratedProtocolMessageType('Vector3', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR3,
  __module__ = 'geometric.vector_pb2'
  # @@protoc_insertion_point(class_scope:choreo.Vector3)
  ))
_sym_db.RegisterMessage(Vector3)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z/github.com/RobotStudio/choreo-msg/msg/geometric'))
# @@protoc_insertion_point(module_scope)
