# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nav/nav.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from primitive import bytes_pb2 as primitive_dot_bytes__pb2
from primitive import float_pb2 as primitive_dot_float__pb2
from primitive import header_pb2 as primitive_dot_header__pb2
from primitive import int_pb2 as primitive_dot_int__pb2
from primitive import string_pb2 as primitive_dot_string__pb2
from geometric import point_pb2 as geometric_dot_point__pb2
from geometric import pose_pb2 as geometric_dot_pose__pb2
from geometric import twist_pb2 as geometric_dot_twist__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='nav/nav.proto',
  package='choreo',
  syntax='proto3',
  serialized_pb=_b('\n\rnav/nav.proto\x12\x06\x63horeo\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15primitive/bytes.proto\x1a\x15primitive/float.proto\x1a\x16primitive/header.proto\x1a\x13primitive/int.proto\x1a\x16primitive/string.proto\x1a\x15geometric/point.proto\x1a\x14geometric/pose.proto\x1a\x15geometric/twist.proto\"\x94\x01\n\tGridCells\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.choreo.Header\x12#\n\ncell_width\x18\x02 \x01(\x0b\x32\x0f.choreo.Float64\x12$\n\x0b\x63\x65ll_height\x18\x03 \x01(\x0b\x32\x0f.choreo.Float64\x12\x1c\n\x05\x63\x65lls\x18\x04 \x03(\x0b\x32\r.choreo.Point\"\xc2\x01\n\x0bMapMetaData\x12\x31\n\rmap_load_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12#\n\nresolution\x18\x02 \x01(\x0b\x32\x0f.choreo.Float32\x12\x1d\n\x05width\x18\x03 \x01(\x0b\x32\x0e.choreo.UInt32\x12\x1e\n\x06height\x18\x04 \x01(\x0b\x32\x0e.choreo.UInt32\x12\x1c\n\x06origin\x18\x05 \x01(\x0b\x32\x0c.choreo.Pose\"o\n\rOccupancyGrid\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.choreo.Header\x12!\n\x04info\x18\x02 \x01(\x0b\x32\x13.choreo.MapMetaData\x12\x1b\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\r.choreo.Bytes\"\xa8\x01\n\x08Odometry\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.choreo.Header\x12&\n\x0e\x63hild_frame_id\x18\x02 \x01(\x0b\x32\x0e.choreo.String\x12(\n\x04pose\x18\x03 \x01(\x0b\x32\x1a.choreo.PoseWithCovariance\x12*\n\x05twist\x18\x04 \x01(\x0b\x32\x1b.choreo.TwistWithCovariance\"C\n\x04Path\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.choreo.Header\x12\x1b\n\x05poses\x18\x02 \x03(\x0b\x32\x0c.choreo.Pose\"{\n\x0eGetPlanRequest\x12\"\n\x05start\x18\x01 \x01(\x0b\x32\x13.choreo.PoseStamped\x12!\n\x04goal\x18\x02 \x01(\x0b\x32\x13.choreo.PoseStamped\x12\"\n\ttolerance\x18\x03 \x01(\x0b\x32\x0f.choreo.Float32\"l\n\rSetMapRequest\x12\"\n\x03map\x18\x01 \x01(\x0b\x32\x15.choreo.OccupancyGrid\x12\x37\n\x0cinitial_pose\x18\x02 \x01(\x0b\x32!.choreo.PoseWithCovarianceStampedB+Z)github.com/RobotStudio/choreo-msg/msg/navb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,primitive_dot_bytes__pb2.DESCRIPTOR,primitive_dot_float__pb2.DESCRIPTOR,primitive_dot_header__pb2.DESCRIPTOR,primitive_dot_int__pb2.DESCRIPTOR,primitive_dot_string__pb2.DESCRIPTOR,geometric_dot_point__pb2.DESCRIPTOR,geometric_dot_pose__pb2.DESCRIPTOR,geometric_dot_twist__pb2.DESCRIPTOR,])




_GRIDCELLS = _descriptor.Descriptor(
  name='GridCells',
  full_name='choreo.GridCells',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='choreo.GridCells.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cell_width', full_name='choreo.GridCells.cell_width', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cell_height', full_name='choreo.GridCells.cell_height', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cells', full_name='choreo.GridCells.cells', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=390,
)


_MAPMETADATA = _descriptor.Descriptor(
  name='MapMetaData',
  full_name='choreo.MapMetaData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='map_load_time', full_name='choreo.MapMetaData.map_load_time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resolution', full_name='choreo.MapMetaData.resolution', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='choreo.MapMetaData.width', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='choreo.MapMetaData.height', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='origin', full_name='choreo.MapMetaData.origin', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=587,
)


_OCCUPANCYGRID = _descriptor.Descriptor(
  name='OccupancyGrid',
  full_name='choreo.OccupancyGrid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='choreo.OccupancyGrid.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='info', full_name='choreo.OccupancyGrid.info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='choreo.OccupancyGrid.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=589,
  serialized_end=700,
)


_ODOMETRY = _descriptor.Descriptor(
  name='Odometry',
  full_name='choreo.Odometry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='choreo.Odometry.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='child_frame_id', full_name='choreo.Odometry.child_frame_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='choreo.Odometry.pose', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='twist', full_name='choreo.Odometry.twist', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=703,
  serialized_end=871,
)


_PATH = _descriptor.Descriptor(
  name='Path',
  full_name='choreo.Path',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='choreo.Path.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='poses', full_name='choreo.Path.poses', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=873,
  serialized_end=940,
)


_GETPLANREQUEST = _descriptor.Descriptor(
  name='GetPlanRequest',
  full_name='choreo.GetPlanRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='choreo.GetPlanRequest.start', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='goal', full_name='choreo.GetPlanRequest.goal', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tolerance', full_name='choreo.GetPlanRequest.tolerance', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=942,
  serialized_end=1065,
)


_SETMAPREQUEST = _descriptor.Descriptor(
  name='SetMapRequest',
  full_name='choreo.SetMapRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='map', full_name='choreo.SetMapRequest.map', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='initial_pose', full_name='choreo.SetMapRequest.initial_pose', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1067,
  serialized_end=1175,
)

_GRIDCELLS.fields_by_name['header'].message_type = primitive_dot_header__pb2._HEADER
_GRIDCELLS.fields_by_name['cell_width'].message_type = primitive_dot_float__pb2._FLOAT64
_GRIDCELLS.fields_by_name['cell_height'].message_type = primitive_dot_float__pb2._FLOAT64
_GRIDCELLS.fields_by_name['cells'].message_type = geometric_dot_point__pb2._POINT
_MAPMETADATA.fields_by_name['map_load_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_MAPMETADATA.fields_by_name['resolution'].message_type = primitive_dot_float__pb2._FLOAT32
_MAPMETADATA.fields_by_name['width'].message_type = primitive_dot_int__pb2._UINT32
_MAPMETADATA.fields_by_name['height'].message_type = primitive_dot_int__pb2._UINT32
_MAPMETADATA.fields_by_name['origin'].message_type = geometric_dot_pose__pb2._POSE
_OCCUPANCYGRID.fields_by_name['header'].message_type = primitive_dot_header__pb2._HEADER
_OCCUPANCYGRID.fields_by_name['info'].message_type = _MAPMETADATA
_OCCUPANCYGRID.fields_by_name['data'].message_type = primitive_dot_bytes__pb2._BYTES
_ODOMETRY.fields_by_name['header'].message_type = primitive_dot_header__pb2._HEADER
_ODOMETRY.fields_by_name['child_frame_id'].message_type = primitive_dot_string__pb2._STRING
_ODOMETRY.fields_by_name['pose'].message_type = geometric_dot_pose__pb2._POSEWITHCOVARIANCE
_ODOMETRY.fields_by_name['twist'].message_type = geometric_dot_twist__pb2._TWISTWITHCOVARIANCE
_PATH.fields_by_name['header'].message_type = primitive_dot_header__pb2._HEADER
_PATH.fields_by_name['poses'].message_type = geometric_dot_pose__pb2._POSE
_GETPLANREQUEST.fields_by_name['start'].message_type = geometric_dot_pose__pb2._POSESTAMPED
_GETPLANREQUEST.fields_by_name['goal'].message_type = geometric_dot_pose__pb2._POSESTAMPED
_GETPLANREQUEST.fields_by_name['tolerance'].message_type = primitive_dot_float__pb2._FLOAT32
_SETMAPREQUEST.fields_by_name['map'].message_type = _OCCUPANCYGRID
_SETMAPREQUEST.fields_by_name['initial_pose'].message_type = geometric_dot_pose__pb2._POSEWITHCOVARIANCESTAMPED
DESCRIPTOR.message_types_by_name['GridCells'] = _GRIDCELLS
DESCRIPTOR.message_types_by_name['MapMetaData'] = _MAPMETADATA
DESCRIPTOR.message_types_by_name['OccupancyGrid'] = _OCCUPANCYGRID
DESCRIPTOR.message_types_by_name['Odometry'] = _ODOMETRY
DESCRIPTOR.message_types_by_name['Path'] = _PATH
DESCRIPTOR.message_types_by_name['GetPlanRequest'] = _GETPLANREQUEST
DESCRIPTOR.message_types_by_name['SetMapRequest'] = _SETMAPREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GridCells = _reflection.GeneratedProtocolMessageType('GridCells', (_message.Message,), dict(
  DESCRIPTOR = _GRIDCELLS,
  __module__ = 'nav.nav_pb2'
  # @@protoc_insertion_point(class_scope:choreo.GridCells)
  ))
_sym_db.RegisterMessage(GridCells)

MapMetaData = _reflection.GeneratedProtocolMessageType('MapMetaData', (_message.Message,), dict(
  DESCRIPTOR = _MAPMETADATA,
  __module__ = 'nav.nav_pb2'
  # @@protoc_insertion_point(class_scope:choreo.MapMetaData)
  ))
_sym_db.RegisterMessage(MapMetaData)

OccupancyGrid = _reflection.GeneratedProtocolMessageType('OccupancyGrid', (_message.Message,), dict(
  DESCRIPTOR = _OCCUPANCYGRID,
  __module__ = 'nav.nav_pb2'
  # @@protoc_insertion_point(class_scope:choreo.OccupancyGrid)
  ))
_sym_db.RegisterMessage(OccupancyGrid)

Odometry = _reflection.GeneratedProtocolMessageType('Odometry', (_message.Message,), dict(
  DESCRIPTOR = _ODOMETRY,
  __module__ = 'nav.nav_pb2'
  # @@protoc_insertion_point(class_scope:choreo.Odometry)
  ))
_sym_db.RegisterMessage(Odometry)

Path = _reflection.GeneratedProtocolMessageType('Path', (_message.Message,), dict(
  DESCRIPTOR = _PATH,
  __module__ = 'nav.nav_pb2'
  # @@protoc_insertion_point(class_scope:choreo.Path)
  ))
_sym_db.RegisterMessage(Path)

GetPlanRequest = _reflection.GeneratedProtocolMessageType('GetPlanRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETPLANREQUEST,
  __module__ = 'nav.nav_pb2'
  # @@protoc_insertion_point(class_scope:choreo.GetPlanRequest)
  ))
_sym_db.RegisterMessage(GetPlanRequest)

SetMapRequest = _reflection.GeneratedProtocolMessageType('SetMapRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETMAPREQUEST,
  __module__ = 'nav.nav_pb2'
  # @@protoc_insertion_point(class_scope:choreo.SetMapRequest)
  ))
_sym_db.RegisterMessage(SetMapRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z)github.com/RobotStudio/choreo-msg/msg/nav'))
# @@protoc_insertion_point(module_scope)
